{% set name = "numpy-stl" %}
{% set version = "3.2.0" %}
{% set sha256 = "5a20c3f79cddaa0abc6a4b99f5486aceed4f88152f29b19a57acc844e183fd4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - stl = stl.main:main
    - stl2ascii = stl.main:to_ascii
    - stl2bin = stl.main:to_binary

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy {{ numpy }}
    - pytest-runner
  run:
    - python
    - numpy {{ numpy }}
    - python-utils

test:
  imports:
    - stl

about:
  home: https://github.com/WoLpH/numpy-stl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Library to make reading, writing and modifying both binary and ascii STL files easy.
  description: |
    Simple library to make working with STL files (and 3D objects in general) fast and easy.

    Due to all operations heavily relying on numpy this is one of the fastest STL editing libraries for Python available.

  doc_url: https://numpy-stl.readthedocs.io
  dev_url: https://github.com/WoLpH/numpy-stl

extra:
  recipe-maintainers:
    - csachs
    - WoLpH
    - gouarin
