{% set name = "numpy-stl" %}
{% set version = "2.8.0" %}
{% set sha256 = "7e0cda4354e7ac8d5aa3224818ab72c344f18b41158d180354dcb6918294c907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - stl = stl.main:main
    - stl2ascii = stl.main:to_ascii
    - stl2bin = stl.main:to_binary

requirements:
  build:
    - {{ compiler('c') }}
    - cython
  host:
    - python
    - setuptools
    - pip
    - numpy
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-utils
    - enum34  # [py2k]

test:
  imports:
    - stl

about:
  home: https://github.com/WoLpH/numpy-stl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Library to make reading, writing and modifying both binary and ascii STL files easy.'
  description: |
    Simple library to make working with STL files (and 3D objects in general) fast and easy.
    
    Due to all operations heavily relying on numpy this is one of the fastest STL editing libraries for Python available.
    
  doc_url: https://numpy-stl.readthedocs.io
  dev_url: https://github.com/WoLpH/numpy-stl

extra:
  recipe-maintainers:
    - csachs
    - WoLpH
